# Generated by Django 4.2.5 on 2023-11-16 16:00

from django.db import migrations, models
import rules.contrib.models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="School",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        blank=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Distinctive name of the school",
                        max_length=100,
                        unique=True,
                        verbose_name="School",
                    ),
                ),
            ],
            options={
                "verbose_name": "School",
                "verbose_name_plural": "Schools",
                "ordering": ["name"],
            },
            bases=(rules.contrib.models.RulesModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name="Campaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        blank=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Distinctive name of the campaign",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "stamp_start",
                    models.DateTimeField(
                        help_text="Instant when the campaign becomes active"
                    ),
                ),
                (
                    "stamp_end",
                    models.DateTimeField(
                        help_text="Instant when the campaign stops to be active"
                    ),
                ),
                ("survey", models.JSONField(default=dict)),
                (
                    "schools",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Schools this campaign is about",
                        related_name="campaigns",
                        to="mosurv.school",
                    ),
                ),
            ],
            options={
                "verbose_name": "Campaign",
                "verbose_name_plural": "Campaigns",
            },
            bases=(rules.contrib.models.RulesModelMixin, models.Model),
        ),
    ]
