# Generated by Django 4.2.5 on 2023-11-16 17:47

from django.db import migrations, models
import django.db.models.deletion
import rules.contrib.models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("mosurv", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaign",
            name="uuid",
            field=models.UUIDField(blank=True, default=uuid.uuid4, unique=True),
        ),
        migrations.AlterField(
            model_name="school",
            name="uuid",
            field=models.UUIDField(blank=True, default=uuid.uuid4, unique=True),
        ),
        migrations.CreateModel(
            name="Survey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.JSONField(default=dict)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="surveys",
                        to="mosurv.campaign",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="surveys",
                        to="mosurv.school",
                    ),
                ),
            ],
            options={
                "verbose_name": "Survey",
                "verbose_name_plural": "Surveys",
            },
            bases=(rules.contrib.models.RulesModelMixin, models.Model),
        ),
    ]
