# Generated by Django 4.2.5 on 2023-11-16 18:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("mosurv", "0002_alter_campaign_uuid_alter_school_uuid_survey"),
    ]

    operations = [
        migrations.AddField(
            model_name="survey",
            name="kind",
            field=models.CharField(
                blank=True,
                choices=[("forth", "Forth"), ("back", "Back")],
                default="forth",
                max_length=50,
                verbose_name="Kind",
            ),
        ),
        migrations.AddField(
            model_name="survey",
            name="user",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="surveys",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="campaign",
            name="survey",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="survey",
            name="content",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterUniqueTogether(
            name="survey",
            unique_together={("kind", "user", "campaign", "school")},
        ),
    ]
