# Generated by Django 4.2.5 on 2023-11-22 13:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mosurv", "0003_survey_kind_survey_user_alter_campaign_survey_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="school",
            name="address",
            field=models.CharField(
                blank=True,
                help_text="Complete address of the school",
                max_length=300,
                null=True,
                verbose_name="Address",
            ),
        ),
        migrations.AddField(
            model_name="school",
            name="code",
            field=models.CharField(
                blank=True,
                help_text="Unique code of the school",
                max_length=20,
                null=True,
                unique=True,
                verbose_name="Code",
            ),
        ),
        migrations.AddField(
            model_name="school",
            name="lat",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="school",
            name="lng",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
