# Generated by Django 4.2.5 on 2024-01-18 13:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mosurv", "0004_school_address_school_code_school_lat_school_lng"),
    ]

    operations = [
        migrations.AddField(
            model_name="survey",
            name="stamp",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
