# Generated by Django 4.2.5 on 2024-01-18 14:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mosurv", "0005_survey_stamp"),
    ]

    operations = [
        migrations.AddField(
            model_name="survey",
            name="status",
            field=models.IntegerField(
                choices=[
                    (-100, "Cancelled"),
                    (0, "Empty"),
                    (50, "Filled"),
                    (100, "Used"),
                ],
                default=0,
            ),
        ),
    ]
