# Generated by Django 4.2.5 on 2024-01-21 19:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mosurv", "0006_survey_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="campaign",
            options={
                "ordering": ["-stamp_start", "-stamp_end"],
                "verbose_name": "Campaign",
                "verbose_name_plural": "Campaigns",
            },
        ),
        migrations.AlterField(
            model_name="campaign",
            name="stamp_end",
            field=models.DateTimeField(
                blank=True,
                help_text="Instant when the campaign stops to be active",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="campaign",
            name="stamp_start",
            field=models.DateTimeField(
                blank=True,
                help_text="Instant when the campaign becomes active",
                null=True,
            ),
        ),
    ]
