# Generated by Django 4.2.5 on 2024-03-11 17:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("mosurv", "0007_alter_campaign_options_alter_campaign_stamp_end_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="survey",
            options={
                "ordering": ["status", "campaign", "school", "kind"],
                "verbose_name": "Survey",
                "verbose_name_plural": "Surveys",
            },
        ),
        migrations.AlterField(
            model_name="survey",
            name="campaign",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="surveys",
                to="mosurv.campaign",
            ),
        ),
        migrations.AlterField(
            model_name="survey",
            name="school",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="surveys",
                to="mosurv.school",
            ),
        ),
        migrations.AlterField(
            model_name="survey",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="surveys",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
