# Generated by Django 4.2.5 on 2024-03-11 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("mosurv", "0008_alter_survey_options_alter_survey_campaign_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cascho",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mosurv.campaign",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="mosurv.school"
                    ),
                ),
            ],
            options={
                "db_table": "mosurv_campaign_schools",
            },
        ),
        migrations.AlterField(
            model_name="campaign",
            name="schools",
            field=models.ManyToManyField(
                blank=True,
                help_text="Schools this campaign is about",
                related_name="campaigns",
                through="mosurv.Cascho",
                to="mosurv.school",
            ),
        ),
    ]
