# Generated by Django 4.2.5 on 2024-03-11 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("mosurv", "0009_cascho_alter_campaign_schools"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cascho",
            name="campaign",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="caschos",
                to="mosurv.campaign",
            ),
        ),
        migrations.AlterField(
            model_name="cascho",
            name="school",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="caschos",
                to="mosurv.school",
            ),
        ),
    ]
